### ISSUE TITLE
rendertarget_id not found

### ISSUE THREAD

**Issue by aprowe** [letoram/safespaces#2]
Hello, 
I am getting the error 
```
/home/alexrowe/Repos/safespaces/safespaces/vrsetup.lua:1498: attempt to call global 'rendertarget_id' (a nil value)
```
I was thinking this is possibly due to a arcan version mismatch (I am using arcan 0.5.4) or I have not correctly installed arcan_vr? 
I am running this without a HMD currently, but I would think that the function would still exist without a HMD. 

I would love to contribute and get this working,

Thanks, 
Alex

**Comment by aprowe** [comment]
Ah building Arcan 0.5.4.3 fixed it. Couldn't get 0.5.4.6 or master to work so I used the first version that included `rendertarget_id`

My quest continues :)

**Comment by letoram** [comment]
Sorry for the response time, I'm usually more active on IRC etc. as I try to move away from github mid- long- term. There's been quite a number of relevant changes in master - if it's not working, that's quite alarming. The big thing is that there's some changes in the drm/mesa/etc. stack recently that did not play well with how we set up native graphics, so somewhere in the last quarter+4.15+ above have been quite buggy with more advanced setups.

**Comment by aprowe** [comment]
No worries! 
Here's what I get when I build on master:
```
[ 74%] Linking C executable arcan
CMakeFiles/arcan.dir/platform/posix/psep_open.c.o: In function `release_device':
/home/alexrowe/Repos/arcan/src/platform/posix/psep_open.c:295: undefined reference to `drmDropMaster'
CMakeFiles/arcan.dir/platform/posix/psep_open.c.o: In function `access_device':
/home/alexrowe/Repos/arcan/src/platform/posix/psep_open.c:374: undefined reference to `drmSetMaster'
/home/alexrowe/Repos/arcan/src/platform/posix/psep_open.c:396: undefined reference to `drmSetMaster'
collect2: error: ld returned 1 exit status
```
