### ISSUE TITLE
Rotating screen for VR

### ISSUE THREAD

**Issue by der-b** [letoram/safespaces#5]
Hi,

i currently work on a DIY VR-Set (https://github.com/OpenHMD/OpenHMD/pull/165) and i use a screen which is more high than width. Therefore i had to rotate the video output somehow. I attached my first solution:
[vrsetup.patch.txt](https://github.com/letoram/safespaces/files/2349812/vrsetup.patch.txt)
I rotated the surfaces on which the images for the eyes are rendered.

What do you think about it? Is this the right way to do this? If yes i would rewrite the code so and add new configuration option.

Kind regarts

Bernd

**Comment by letoram** [comment]
First - cool project!

Second, I assume you are using this with the egl-dri platform? (for X11 setting a window with the dimensions / AR window and xrandr to rotate or fullscreen should work without any modification).
If so - there is an easier option, that you can try first - https://github.com/letoram/safespaces/blob/master/safespaces/safespaces.lua#L137
map_video_display takes an optional third argument that can set rotation:
https://github.com/letoram/arcan/blob/master/doc/map_video_display.lua

Third, you might also want to play around with having the IMU sampled as part of arcan_vr - I've been meaning to do that for another IMU (adafruit BNO055) and have an option to define which virtual 'limb' that maps to.

**Comment by der-b** [comment]
I did a quick test by adding HINT_ROTATE_CCW_90 to map_video_dispaly at
https://github.com/letoram/safespaces/blob/master/safespaces/safespaces.lua#L137
and at
https://github.com/letoram/safespaces/blob/master/safespaces/safespaces.lua#L141

but it didn't worked. It worked after i added the parameter to 
https://github.com/letoram/safespaces/blob/master/safespaces/suppl.lua#L189
I did not further investigate that.


Unfortunately, the quality of the rendered images seems to be much better with my solution than by adding HINT_ROTATE_CCW_90. It seems to be, that the rendered image is somehow scaled with HINT_ROTATE_CCW_90.

**Comment by letoram** [comment]
You might net to bit.bor in HINT_CROP - but if it doesn't work, figuring out why the stretched blit occurs is probably not worth it - a cleaned up version of your approach (so specifying output layout) is more than sufficient imo.

**Comment by der-b** [comment]
"bit.bor(HINT_ROTATE_CCW_90, HINT_CROP)" doesn't work for me. Therefore i created cleaned up version (https://github.com/der-b/safespaces/commit/aa3741d7d4bbf172d742c43f2bd6f9a8c8a6f058).

I hesitate to create an pull request, because my intuitive implementation of "cw90" rotates in the same direction as HINT_ROTATE_CCW_90 and my "ccw90" rotates in the same direction as HINT_ROTATE_CW_90. I think i messed up something.

Is my interpretation of CW == clockwise and CCW == counterclockwise correct?
